/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldMetaModel } from './fieldMetaModel';


export interface AccountMetaModel { 
    fields?: { [key: string]: FieldMetaModel; };
}
