/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountItem { 
    accountId?: string;
    accountName?: string;
    accountPurpose?: string;
    accountSetupStatus?: string;
    accountType?: string;
    actions?: Array<AccountItem.ActionsEnum>;
    clientId?: string;
    closingDate?: string;
    sourceAccountId?: string;
    terminationDate?: string;
}
export namespace AccountItem {
    export type ActionsEnum = 'EDIT' | 'CLOSING' | 'CLONE' | 'CLOSED' | 'INACTIVE' | 'ACTIVE' | 'VIEW' | 'EXPORT_ACCOUNT';
    export const ActionsEnum = {
        EDIT: 'EDIT' as ActionsEnum,
        CLOSING: 'CLOSING' as ActionsEnum,
        CLONE: 'CLONE' as ActionsEnum,
        CLOSED: 'CLOSED' as ActionsEnum,
        INACTIVE: 'INACTIVE' as ActionsEnum,
        ACTIVE: 'ACTIVE' as ActionsEnum,
        VIEW: 'VIEW' as ActionsEnum,
        EXPORTACCOUNT: 'EXPORT_ACCOUNT' as ActionsEnum
    };
}
