/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApprovalRequest { 
    accountCreatedBy?: string;
    accountId?: string;
    accountName?: string;
    accountType?: string;
    action?: ApprovalRequest.ActionEnum;
    approvalActions?: Array<ApprovalRequest.ApprovalActionsEnum>;
    approver?: string;
    comment?: string;
    id?: string;
    sourceAccountId?: string;
    submittedForApprovalDate?: string;
}
export namespace ApprovalRequest {
    export type ActionEnum = 'CREATE_ACC' | 'CREATE_OPS' | 'CHANGE_ACC' | 'CHANGE_OPS' | 'CLOSING' | 'CLOSED' | 'INACTIVE' | 'ACTIVE';
    export const ActionEnum = {
        CREATEACC: 'CREATE_ACC' as ActionEnum,
        CREATEOPS: 'CREATE_OPS' as ActionEnum,
        CHANGEACC: 'CHANGE_ACC' as ActionEnum,
        CHANGEOPS: 'CHANGE_OPS' as ActionEnum,
        CLOSING: 'CLOSING' as ActionEnum,
        CLOSED: 'CLOSED' as ActionEnum,
        INACTIVE: 'INACTIVE' as ActionEnum,
        ACTIVE: 'ACTIVE' as ActionEnum
    };
    export type ApprovalActionsEnum = 'REVOKE' | 'APPROVE_OR_REJECT';
    export const ApprovalActionsEnum = {
        REVOKE: 'REVOKE' as ApprovalActionsEnum,
        APPROVEORREJECT: 'APPROVE_OR_REJECT' as ApprovalActionsEnum
    };
}
