/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';


export interface Approval { 
    accountChanges?: Account;
    action?: string;
    approver?: string;
    closingDate?: string;
    comment?: string;
    id?: string;
    requester?: string;
    status?: string;
    submittedDate?: string;
    terminationDate?: string;
}
