/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApprovalContent } from './approvalContent';


export interface ClosingWithTerminationDateApproval { 
    approvalContent?: ApprovalContent;
    closingDate?: string;
    terminationDate?: string;
}
