/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorPath } from './errorPath';


export interface ErrorDescription { 
    errors?: Array<string>;
    paths?: Array<ErrorPath>;
}
