/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Step } from './step';


export interface FieldOrdering { 
    section?: FieldOrdering.SectionEnum;
    section2Steps?: { [key: string]: Array<Step>; };
}
export namespace FieldOrdering {
    export type SectionEnum = 'KEY_DETAILS' | 'INVESTMENT_PARTNERS' | 'ASSETS_AND_REPORTING' | 'PERFORMANCE_AND_BENCHMARKS' | 'BUISINESS_RULES' | 'PRIVATE_MARKET' | 'FUND_AND_ENTITY' | 'NONE';
    export const SectionEnum = {
        KEYDETAILS: 'KEY_DETAILS' as SectionEnum,
        INVESTMENTPARTNERS: 'INVESTMENT_PARTNERS' as SectionEnum,
        ASSETSANDREPORTING: 'ASSETS_AND_REPORTING' as SectionEnum,
        PERFORMANCEANDBENCHMARKS: 'PERFORMANCE_AND_BENCHMARKS' as SectionEnum,
        BUISINESSRULES: 'BUISINESS_RULES' as SectionEnum,
        PRIVATEMARKET: 'PRIVATE_MARKET' as SectionEnum,
        FUNDANDENTITY: 'FUND_AND_ENTITY' as SectionEnum,
        NONE: 'NONE' as SectionEnum
    };
}
