/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PolicyTree { 
    accountId?: string;
    accountName?: string;
    borVersions?: string;
    comments?: string;
    effectiveCloseDate?: string;
    effectiveOpenDate?: string;
    enteredApprover?: string;
    enteredDate?: string;
    enteredUser?: string;
    lastApprover?: string;
    lastUserDate?: string;
    lastUserUpdate?: string;
    owner?: string;
    policyTreeType?: string;
    purpose?: string;
    status?: string;
}
