export * from './accountController.service';
import { AccountControllerService } from './accountController.service';
export * from './approvalController.service';
import { ApprovalControllerService } from './approvalController.service';
export * from './basicErrorController.service';
import { BasicErrorControllerService } from './basicErrorController.service';
export * from './bulkUploadController.service';
import { BulkUploadControllerService } from './bulkUploadController.service';
export * from './clientWorkflowController.service';
import { ClientWorkflowControllerService } from './clientWorkflowController.service';
export * from './exportController.service';
import { ExportControllerService } from './exportController.service';
export * from './listOfAccountsController.service';
import { ListOfAccountsControllerService } from './listOfAccountsController.service';
export * from './policyTreeController.service';
import { PolicyTreeControllerService } from './policyTreeController.service';
export * from './policyTreeDesignController.service';
import { PolicyTreeDesignControllerService } from './policyTreeDesignController.service';
export * from './securityController.service';
import { SecurityControllerService } from './securityController.service';
export * from './testController.service';
import { TestControllerService } from './testController.service';
export const APIS = [AccountControllerService, ApprovalControllerService, BasicErrorControllerService, BulkUploadControllerService, ClientWorkflowControllerService, ExportControllerService, ListOfAccountsControllerService, PolicyTreeControllerService, PolicyTreeDesignControllerService, SecurityControllerService, TestControllerService];
