/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Account } from '../model/account';
import { ApprovalContent } from '../model/approvalContent';
import { ClosingWithTerminationDateApproval } from '../model/closingWithTerminationDateApproval';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class ClientWorkflowControllerService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath || basePath || this.basePath;

        } else {
            this.configuration.basePath = basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * activateAccount
     * 
     * @param accountId accountId
     * @param userId userId
     * @param approvalContent approvalContent
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public activateAccountUsingPOST(accountId: string, userId: string, approvalContent: ApprovalContent, observe?: 'body', reportProgress?: boolean): Observable<Account>;
    public activateAccountUsingPOST(accountId: string, userId: string, approvalContent: ApprovalContent, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Account>>;
    public activateAccountUsingPOST(accountId: string, userId: string, approvalContent: ApprovalContent, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Account>>;
    public activateAccountUsingPOST(accountId: string, userId: string, approvalContent: ApprovalContent, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accountId === null || accountId === undefined) {
            throw new Error('Required parameter accountId was null or undefined when calling activateAccountUsingPOST.');
        }
        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling activateAccountUsingPOST.');
        }
        if (approvalContent === null || approvalContent === undefined) {
            throw new Error('Required parameter approvalContent was null or undefined when calling activateAccountUsingPOST.');
        }

        let headers = this.defaultHeaders;
        if (userId !== undefined && userId !== null) {
            headers = headers.set('userId', String(userId));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Account>(`${this.configuration.basePath}/clientworkflow/activate/${encodeURIComponent(String(accountId))}`,
            approvalContent,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * closeAccount
     * 
     * @param accountId accountId
     * @param userId userId
     * @param closingWithTerminationDateApproval closingWithTerminationDateApproval
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public closeAccountUsingPOST(accountId: string, userId: string, closingWithTerminationDateApproval: ClosingWithTerminationDateApproval, observe?: 'body', reportProgress?: boolean): Observable<Account>;
    public closeAccountUsingPOST(accountId: string, userId: string, closingWithTerminationDateApproval: ClosingWithTerminationDateApproval, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Account>>;
    public closeAccountUsingPOST(accountId: string, userId: string, closingWithTerminationDateApproval: ClosingWithTerminationDateApproval, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Account>>;
    public closeAccountUsingPOST(accountId: string, userId: string, closingWithTerminationDateApproval: ClosingWithTerminationDateApproval, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accountId === null || accountId === undefined) {
            throw new Error('Required parameter accountId was null or undefined when calling closeAccountUsingPOST.');
        }
        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling closeAccountUsingPOST.');
        }
        if (closingWithTerminationDateApproval === null || closingWithTerminationDateApproval === undefined) {
            throw new Error('Required parameter closingWithTerminationDateApproval was null or undefined when calling closeAccountUsingPOST.');
        }

        let headers = this.defaultHeaders;
        if (userId !== undefined && userId !== null) {
            headers = headers.set('userId', String(userId));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Account>(`${this.configuration.basePath}/clientworkflow/close/${encodeURIComponent(String(accountId))}`,
            closingWithTerminationDateApproval,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * closingAccount
     * 
     * @param accountId accountId
     * @param userId userId
     * @param closingWithTerminationDateApproval closingWithTerminationDateApproval
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public closingAccountUsingPOST(accountId: string, userId: string, closingWithTerminationDateApproval: ClosingWithTerminationDateApproval, observe?: 'body', reportProgress?: boolean): Observable<Account>;
    public closingAccountUsingPOST(accountId: string, userId: string, closingWithTerminationDateApproval: ClosingWithTerminationDateApproval, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Account>>;
    public closingAccountUsingPOST(accountId: string, userId: string, closingWithTerminationDateApproval: ClosingWithTerminationDateApproval, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Account>>;
    public closingAccountUsingPOST(accountId: string, userId: string, closingWithTerminationDateApproval: ClosingWithTerminationDateApproval, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accountId === null || accountId === undefined) {
            throw new Error('Required parameter accountId was null or undefined when calling closingAccountUsingPOST.');
        }
        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling closingAccountUsingPOST.');
        }
        if (closingWithTerminationDateApproval === null || closingWithTerminationDateApproval === undefined) {
            throw new Error('Required parameter closingWithTerminationDateApproval was null or undefined when calling closingAccountUsingPOST.');
        }

        let headers = this.defaultHeaders;
        if (userId !== undefined && userId !== null) {
            headers = headers.set('userId', String(userId));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Account>(`${this.configuration.basePath}/clientworkflow/closing/${encodeURIComponent(String(accountId))}`,
            closingWithTerminationDateApproval,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deactivateAccount
     * 
     * @param accountId accountId
     * @param userId userId
     * @param closingWithTerminationDateApproval closingWithTerminationDateApproval
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deactivateAccountUsingPOST(accountId: string, userId: string, closingWithTerminationDateApproval: ClosingWithTerminationDateApproval, observe?: 'body', reportProgress?: boolean): Observable<Account>;
    public deactivateAccountUsingPOST(accountId: string, userId: string, closingWithTerminationDateApproval: ClosingWithTerminationDateApproval, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Account>>;
    public deactivateAccountUsingPOST(accountId: string, userId: string, closingWithTerminationDateApproval: ClosingWithTerminationDateApproval, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Account>>;
    public deactivateAccountUsingPOST(accountId: string, userId: string, closingWithTerminationDateApproval: ClosingWithTerminationDateApproval, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accountId === null || accountId === undefined) {
            throw new Error('Required parameter accountId was null or undefined when calling deactivateAccountUsingPOST.');
        }
        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling deactivateAccountUsingPOST.');
        }
        if (closingWithTerminationDateApproval === null || closingWithTerminationDateApproval === undefined) {
            throw new Error('Required parameter closingWithTerminationDateApproval was null or undefined when calling deactivateAccountUsingPOST.');
        }

        let headers = this.defaultHeaders;
        if (userId !== undefined && userId !== null) {
            headers = headers.set('userId', String(userId));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Account>(`${this.configuration.basePath}/clientworkflow/deactivate/${encodeURIComponent(String(accountId))}`,
            closingWithTerminationDateApproval,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
